version: '2'
services:
    devlad-app:
        image: devlad
        external_links:
            - devlad-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/devlad
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    devlad-postgresql:
        extends:
            file: postgresql.yml
            service: devlad-postgresql
