version: '2'
services:
    devlad-postgresql:
        container_name: devlad-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/devlad/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=devlad
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
